# Generated by Django 2.2.2 on 2019-06-16 14:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rec_updated', models.DateTimeField(auto_now=True, help_text='The datetime this actual object was updated.', null=True)),
                ('rec_created', models.DateTimeField(auto_now_add=True, help_text='The datetime this actual object was created.', null=True)),
                ('inpatient', models.BooleanField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rec_updated', models.DateTimeField(auto_now=True, help_text='The datetime this actual object was updated.', null=True)),
                ('rec_created', models.DateTimeField(auto_now_add=True, help_text='The datetime this actual object was created.', null=True)),
                ('kind', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['inpatient'], name='core_group_inpatie_a28ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['start_date'], name='core_group_start_d_54efeb_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['end_date'], name='core_group_end_dat_af8f94_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['start_date', 'end_date'], name='core_group_start_d_a2b3dc_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['start_date'], name='core_treatm_start_d_68affe_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['end_date'], name='core_treatm_end_dat_b06027_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['start_date', 'end_date'], name='core_treatm_start_d_f66f11_idx'),
        ),
    ]
